[build]
command = "npm ci && node scripts/set-env.js && npm install @angular-builders/custom-webpack@latest --save-dev && npx ng build --configuration=production --budget-error=999mb"
publish = "dist/whatsapp-clone-ui"

[build.environment]
NODE_VERSION = "18.19.1"