[build]
  command = "npm list -g @angular/cli && npx ng version && npm install -g @angular/cli@19 && npm ci && npx ng build --configuration=production"
  publish = "dist/whatsapp-clone-ui"
[build.environment]
  NODE_VERSION = "18.19.1"
