[build]
command = "npm ci && npm install @angular-builders/custom-webpack@latest --save-dev && npx ng version && npx ng build --configuration=production"
publish = "dist/whatsapp-clone-ui"

[build.environment]
NODE_VERSION = "18.19.1"